### ISSUE TITLE
Error with Python >= 3.11

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup-client-aiortc#22]
mediasoup-client-aiortc fails with Python >= 3.11. This happens when running the tests in macOS Intel and ARM with Python 3.11:

```
$ DEBUG="*WARN* *ERROR*" npm test

      mediasoup-client:ERROR:aiortc:Channel send Channel error: Error: write EPIPE +0ms

      94 |         });
      95 |         this._sendSocket.on('end', () => (logger.debug('send Channel ended by the worker process')));
    > 96 |         this._sendSocket.on('error', (error) => (logger.error('send Channel error: %s', String(error))));
         |                                                         ^
      97 |         this._recvSocket.on('end', () => (logger.debug('receive Channel ended by the worker process')));
      98 |         this._recvSocket.on('error', (error) => (logger.error('receive Channel error: %s', String(error))));
      99 |     }

      at Logger.apply [as _error] (node_modules/debug/src/common.js:113:10)
      at Socket.error (lib/Channel.js:96:57)

  console.error
      mediasoup-client:ERROR:aiortc:Worker worker process died unexpectedly [pid:70329, code:0, signal:null] +0ms

      108 |             }
      109 |             else {
    > 110 |                 logger.error('worker process died unexpectedly [pid:%s, code:%s, signal:%s]', this._pid, code, signal);
          |                        ^
      111 |                 this.safeEmit('died', new Error(`[pid:${this._pid}, code:${code}, signal:${signal}]`));
      112 |             }
      113 |         });

```

As a workaround, we can force Python 3.10 as follows (this is in macOS with Hombrew):

```
# Install Python 3.10
brew install python@3.10

# export envs
export PYTHON=python3.10 
export PIP=pip3.10

# Install Python deps using Python 3.10
pip3.10 install aiortc pynetstring

# Install NPM deps now
npm i

# Run tests
npm test
```

### NOTE: CI fails due to this issue

CI fails in macOS hosts, probably due to Python > 3.10. So we may fix this issue entirely or add a workaround in the CI file to force usage of Python 3.10.

**Comment by ibc** [comment]
**MORE INFO:**

NOTE: This is in PR https://github.com/versatica/mediasoup-client-aiortc/pull/26 but anyway.

Using Python 3.11 (default one in current macOS), let's enable `PYTHON_LOG_TO_STDOUT=true` env to make Python directly log to stdout/stderr:

```
$ PYTHON_LOG_TO_STDOUT=true nt

> mediasoup-client-aiortc@3.8.1 test
> node npm-scripts.mjs test

npm-scripts [INFO] [test] replaceVersion()
npm-scripts [INFO] [test] replaceNodeVersion()
npm-scripts [INFO] [test] replacePythonVersion()
npm-scripts [INFO] [test] test()
npm-scripts [INFO] [test] executeCmd(): jest --runInBand

 RUNS  src/tests/test.ts
worker: starting mediasoup-client aiortc worker
Using selector: KqueueSelector
worker: run()
channel: socket closed, exiting
worker: run() done
worker: shutdown()
Traceback (most recent call last):
  File "/private/tmp/mediasoup-client-aiortc/worker/worker.py", line 297, in <module>
    loop.run_until_complete(
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/private/tmp/mediasoup-client-aiortc/worker/worker.py", line 269, in shutdown
    await channel.close()
  File "/private/tmp/mediasoup-client-aiortc/worker/channel.py", line 69, in close
    self._reader.close()
```

**Comment by ibc** [comment]
It's amazing because in that branch I've removed the call `self._reader.close()` in `handler.py` so I DO NOT UNDERSTAND.
