### ISSUE TITLE
Error when trying to pause a consumer.

### ISSUE THREAD

**Issue by ggoldens** [versatica/mediasoup-client-aiortc#28]
The request 'handler.setTrackDirection' fails when calling `consumer.pause()`.

```
mediasoup-client-aiortc:WARN:Channel request failed [method:handler.setTrackDirection, id:23]: KeyError: '0'
```

STR:
1) add this test to test.js, just before the test `'consumer.close() succeed'`:
```
test('consumer.pause() succeed', () =>
{
	audioConsumer.pause();

	expect(audioConsumer.paused).toBe(true);
});
```

Run it like this so that you can see the error. `DEBUG="*WARN*" npm run test`.
The tests will pass, but you will see this:
```
Test Suites: 1 passed, 1 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        1.363 s, estimated 2 s
Ran all test suites.
  console.warn
      mediasoup-client-aiortc:WARN:Channel request failed [method:handler.setTrackDirection, id:57]: KeyError: '0' +0ms

      218 | 					}
      219 |
    > 220 | 					clearTimeout(sent.timer);
          | 					                  ^
      221 | 					pReject(error);
      222 | 				},
      223 | 				timer : setTimeout(() =>

      at Logger.debug (node_modules/debug/src/common.js:113:10)
      at Channel.processMessage (src/Channel.ts:220:24)
      at Socket.<anonymous> (src/Channel.ts:96:26)

```

The issue is that the handler `handler.setTrackDirection` in handler.py attempts to find the localId in `self._sendTransceivers`. The localId is 0 or 1 (audio or video), and that localId doesn't exist in _sendTransceivers dict, so the transceiver is not found.

There's probably a missing mechanism to handle the setTrackDirection for receiver tracks.

**Comment by ibc** [comment]
Running the `consumer.pause()` test above with `PYTHON_LOG_TO_STDOUT=true` I see:

```
worker: processRequest() [method:handler.setTrackDirection]
worker: request 'handler.setTrackDirection' failed: KeyError: '0'
  File "/Users/ibc/src/mediasoup-client-aiortc/worker/worker.py", line 236, in run
    result = await processRequest(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ibc/src/mediasoup-client-aiortc/worker/worker.py", line 168, in processRequest
    return await handler.processRequest(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ibc/src/mediasoup-client-aiortc/worker/handler.py", line 257, in processRequest
    transceiver = self._sendTransceivers[localId]
```

So `handler..py` line 257. Taking a look to it.

**Comment by ibc** [comment]
This is the result of `worker.dump()` before calling `consumer.pause()` in the new added test:

```js
    {
      "handlers": [
        {
          "iceConnectionState": "checking",
          "iceGatheringState": "complete",
          "id": "09569574-b32b-4724-9b4d-5705acb8ca8e",
          "sendTransceivers": [
            {
              "localId": "ffa2df8a-35bf-49ae-b006-64b2aad4229c",
              "mid": "0"
            },
            {
              "localId": "cf3de13b-b8b1-4f17-b580-b96d212859b0",
              "mid": "1"
            },
            {
              "localId": "9c23d37f-7583-4d3e-a17a-43529faff2f2",
              "mid": "3"
            }
          ],
          "signalingState": "stable",
          "transceivers": [
            {
              "currentDirection": "sendonly",
              "direction": "sendrecv",
              "kind": "audio",
              "mid": "0",
              "receiver": {
                "trackId": null
              },
              "sender": {
                "trackId": "02a1d45c-c4ec-43e9-bd0e-981a6390699f"
              },
              "stopped": false
            },
            {
              "currentDirection": "sendonly",
              "direction": "sendrecv",
              "kind": "video",
              "mid": "1",
              "receiver": {
                "trackId": null
              },
              "sender": {
                "trackId": "df937c97-9dfd-4728-8cba-620629cc59b7"
              },
              "stopped": false
            },
            {
              "currentDirection": "sendonly",
              "direction": "sendrecv",
              "kind": "audio",
              "mid": "3",
              "receiver": {
                "trackId": null
              },
              "sender": {
                "trackId": "9c23d37f-7583-4d3e-a17a-43529faff2f2"
              },
              "stopped": false
            }
          ]
        },
        {
          "iceConnectionState": "checking",
          "iceGatheringState": "complete",
          "id": "26e11ff0-b4be-45eb-b21c-9d61cb3462c0",
          "sendTransceivers": [],
          "signalingState": "stable",
          "transceivers": [
            {
              "currentDirection": "recvonly",
              "direction": "recvonly",
              "kind": "audio",
              "mid": "0",
              "receiver": {
                "trackId": "9c23d37f-7583-4d3e-a17a-43529faff2f2"
              },
              "sender": {
                "trackId": null
              },
              "stopped": false
            },
            {
              "currentDirection": "recvonly",
              "direction": "recvonly",
              "kind": "video",
              "mid": "1",
              "receiver": {
                "trackId": "b39e5417-3739-4285-aa84-e41faa621d59"
              },
              "sender": {
                "trackId": null
              },
              "stopped": false
            },
            {
              "currentDirection": "recvonly",
              "direction": "recvonly",
              "kind": "video",
              "mid": "probator",
              "receiver": {
                "trackId": "probator"
              },
              "sender": {
                "trackId": null
              },
              "stopped": false
            }
          ]
        }
      ],
      "pid": 46026,
      "players": [
        {
          "audioTrack": {
            "id": "ffa2df8a-35bf-49ae-b006-64b2aad4229c",
            "kind": "audio",
            "readyState": "live"
          },
          "id": "c589f9a9-c3ba-491c-8c39-e7d919e205b1",
          "videoTrack": {
            "id": "cf3de13b-b8b1-4f17-b580-b96d212859b0",
            "kind": "video",
            "readyState": "ended"
          }
        },
        {
          "audioTrack": {
            "id": "02a1d45c-c4ec-43e9-bd0e-981a6390699f",
            "kind": "audio",
            "readyState": "live"
          },
          "id": "a264c28d-1188-44b5-a63c-0c312e0faa9c",
          "videoTrack": {
            "id": "df937c97-9dfd-4728-8cba-620629cc59b7",
            "kind": "video",
            "readyState": "live"
          }
        }
      ]
    }
```

BTW it doesn't make any sense that when we call `consumer.pause()` we check `sendTransceivers` ¯\_(ツ)_/¯. In progress.

**Comment by ibc** [comment]
Basic problem is that in `handler.py` we only fill `self._sendTransceivers` map when producing media (when `transport.produce()` is called). However, `setTrackDirection` request can be called for both a Producer and a Consumer, so here the bug. On it.
